language: [ ruby, node_js ]
rvm: [ 2.1.1 ]
node_js: [ 0.10 ]

before_script:
  - npm install bower -g
  - bower install

install:
  - bundle update

script: bundle exec rake travis

# set the branch that will be built and published to GitHub pages
branches:
  only:
    - source

# create a GitHub Personal Access Token
# install the travis gem
# and run the command below (fill in your name, email, and token)
# $ travis encrypt 'GIT_NAME="Your Name" GIT_EMAIL=you@example.com GH_TOKEN=token'
# replace the value of secure with your generated value
env:
  - secure: "OcV9VkkZ8MGJLpjc1fHV23FHbqlFNQrhRKEPRIKrg/cVcde0RIL3aWNoCnhUJfgnQOZOEoV+OOp/W1SbHafys8kYihc7Y+rVh2jZNcBWE5+OOGZlNXNQV/ZoIjAzaDSaUWcr2Md2KgtoCwkC90LY09JWJ88UuFP86R2RWGKJSC0="
